### ISSUE TITLE
"Parks_Property_2016.csv" is missing from the Nashville data portal

### ISSUE THREAD

**Issue by ngnrfsk** [maxdrohde/blog_quarto#2]
"Parks_Property_2016.csv" is missing from the Nashville data portal, could you maybe provide a link to your original data. Or maybe just use this version of the file I made...

[Parks_Property_2016.csv](https://github.com/maxdrohde/blog_quarto/files/13564971/Parks_Property_2016.csv)

**Comment by maxdrohde** [comment]
Thanks for letting me know! I didn't realize it wasn't on the data portal anymore. The original file is in the `posts` folder here: 
https://github.com/maxdrohde/blog_quarto/tree/main/posts/gganimate-map
